In [1]:
import pandas as pd 
import numpy as np 
from google.colab import drive 

In [3]:
drive.mount('/content/drive/')

Mounted at /content/drive/


In [4]:
diccionario=pd.read_csv('/content/drive/MyDrive/diccionario_b.csv').drop(columns='Unnamed: 0')
diccionario.head(110)

NOMBRE_CAMPO    Claves    Catálogo
0                                               Folio      folio         NaN
1                                             Entidad    entidad    entidad 
2                                             Control    control         NaN
3                               Vivienda seleccionada    viv_sel    viv_sel 
4                                     Número de hogar    num_hog     num_hog
..                                                 ...       ...         ...
103  Status de las personas en condición de lectura...   perslec   cpperslec
104                                 Formato de libros   l_format  cp_formato
105                               Formato de revistas   r_format  cp_formato
106                            Formato de periódicos    p_format  cp_formato
107  Personas lectoras de libros, revistas o periód...  perslecl     c_si_no

[108 rows x 3 columns]

Eliminaremos la pregunta  2 hasta la 32 ya que estas no aportan verdadera información al modelo. Existen datos que hacen ruido en la variable objetivo, (ya que esta solo contiene la clasificación 1 y 2 pero aperece tambien 0)



In [7]:
datos_2022=pd.read_csv('/content/drive/MyDrive/datos_febrero_2022_.csv').drop(columns='Unnamed: 0')
datos_2022_2=datos_2022[(datos_2022['perslecl']>=1)]
datos_2022_2.head(2)

entidad  viv_sel  num_hog  hog_mud  n_ren_el  cd  sexo  edad  nivel  \
0        1        4        1        0         1  14     1    51      6   
1        1        2        1        0         2  14     2    73      2   

   cond_act  ...  p36_2  p36_3  p36_4  h_lec  mat_lec  perslec  l_format  \
0         1  ...      1      1      2      3        3        1         0   
1         7  ...      1      1      2      4        4        2         0   

   r_format  p_format  perslecl  
0         0         0         2  
1         0         0         2  

[2 rows x 78 columns]

In [8]:
datos_2022_2.columns[11:56]

Index(['p2', 'p3_1', 'p3_2', 'p3_3', 'p3_4', 'p3_5', 'p4', 'p5', 'p6_1',
       'p6_2', 'p6_3', 'p6_4', 'p6_5', 'p6_6', 'p7', 'p7_3', 'p8_1', 'p8_2',
       'p9', 'p10', 'p11', 'p13', 'p13_3', 'p14_1', 'p14_2', 'p15', 'p16',
       'p17', 'p19', 'p19_3', 'p20_1', 'p20_2', 'p21', 'p22', 'p23_1', 'p23_2',
       'p24', 'p25', 'p26', 'p27', 'p28', 'p29', 'p30', 'p31', 'p32'],
      dtype='object')

In [9]:
datos_2022_2=datos_2022_2.drop(columns=datos_2022.columns[11:56])

Otros datos más que eliminaremos que no aportan a nuestro modelo

In [10]:
datos_2022_2.columns[26:32]

Index(['h_lec', 'mat_lec', 'perslec', 'l_format', 'r_format', 'p_format'], dtype='object')

In [11]:
datos_2022_2.drop(columns=datos_2022_2.columns[26:32],inplace=True)


In [12]:
datos_2022_2.columns

Index(['entidad', 'viv_sel', 'num_hog', 'hog_mud', 'n_ren_el', 'cd', 'sexo',
       'edad', 'nivel', 'cond_act', 'p1', 'p33_1', 'p33_2', 'p33_3', 'p33_4',
       'p34_1', 'p34_2', 'p34_3', 'p34_3_1', 'p34_4', 'p34_4_1', 'p35',
       'p36_1', 'p36_2', 'p36_3', 'p36_4', 'perslecl'],
      dtype='object')

In [13]:
variables_categoricas=['entidad', 'viv_sel', 'num_hog', 'hog_mud', 'n_ren_el', 'cd', 'sexo', 'cond_act', 'p1','p33_1', 'p33_2', 'p33_3', 'p33_4', 'p34_1', 'p34_2', 'p34_3','p34_3_1',	'p34_4',	'p34_4_1', 'p35',
       'p36_1', 'p36_2', 'p36_3', 'p36_4']

In [14]:
datos_categoricos=datos_2022_2[variables_categoricas]
datos_categoricos

entidad  viv_sel  num_hog  hog_mud  n_ren_el  cd  sexo  cond_act  p1  \
0           1        4        1        0         1  14     1         1   1   
1           1        2        1        0         2  14     2         7   1   
2           1        1        1        0         1  14     1         1   1   
3           1        3        1        0         2  14     2         1   1   
4           1        1        1        0         6  14     2         7   1   
...       ...      ...      ...      ...       ...  ..   ...       ...  ..   
2011       32        3        1        0         2  32     2         7   1   
2012       32        4        1        0         1  32     2         8   1   
2013       32        2        1        0         1  32     1         1   1   
2014       32        1        1        0         1  32     2         9   1   
2015       32        4        1        0         2  32     2         8   1   

      p33_1  ...  p34_2  p34_3  p34_3_1  p34_4  p34_4_1  p35  p36_1  p36_2  \
0         2  ...      1      1        2      1        1    1      1      1   
1         2  ...      2      2        0      1        1    1      1      1   
2         2  ...      2      2        0      1        1    1      1      1   
3         2  ...      2      2        0      2        0    1      1      1   
4         2  ...      2      2        0      1        1    1      1      1   
...     ...  ...    ...    ...      ...    ...      ...  ...    ...    ...   
2011      2  ...      2      2        0      2        0    1      1      1   
2012      2  ...      1      1        2      1        1    1      1      1   
2013      2  ...      1      1        1      1        1    1      2      2   
2014      2  ...      3      3        0      2        0    1      3      3   
2015      2  ...      2      2        0      2        0    1      3      3   

      p36_3  p36_4  
0         1      2  
1         1      2  
2         1      2  
3         1      1  
4         1      1  
...     ...    ...  
2011      1      1  
2012      1      1  
2013      2      2  
2014      3      3  
2015      2      2  

[1979 rows x 24 columns]

In [15]:
from sklearn.preprocessing import OneHotEncoder

In [16]:
procesador=OneHotEncoder(sparse=False)
x=procesador.fit(datos_2022_2[variables_categoricas])

In [17]:
x.categories_

[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]),
 array([1, 2, 3, 4]),
 array([1]),
 array([0, 1, 2, 3]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([ 1,  2,  3,  4,  5,  7,  8,  9, 10, 12, 13, 14, 15, 16, 17, 18, 19,
        21, 24, 25, 26, 27, 28, 29, 31, 32, 33, 36, 39, 40, 41, 43]),
 array([1, 2]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([1]),
 array([1, 2]),
 array([1, 2]),
 array([1, 2]),
 array([1, 2]),
 array([1, 2, 3]),
 array([1, 2, 3]),
 array([1, 2, 3]),
 array([0, 1, 2, 3]),
 array([1, 2, 3]),
 array([0, 1, 2, 3, 4, 5, 6]),
 array([1, 2]),
 array([0, 1, 2, 3]),
 array([0, 1, 2, 3]),
 array([0, 1, 2, 3]),
 array([0, 1, 2, 3])]

In [18]:
y=procesador.transform(datos_categoricos)
nombres=procesador.get_feature_names_out(variables_categoricas)
nombres

array(['entidad_1', 'entidad_2', 'entidad_3', 'entidad_4', 'entidad_5',
       'entidad_6', 'entidad_7', 'entidad_8', 'entidad_9', 'entidad_10',
       'entidad_11', 'entidad_12', 'entidad_13', 'entidad_14',
       'entidad_15', 'entidad_16', 'entidad_17', 'entidad_18',
       'entidad_19', 'entidad_20', 'entidad_21', 'entidad_22',
       'entidad_23', 'entidad_24', 'entidad_25', 'entidad_26',
       'entidad_27', 'entidad_28', 'entidad_29', 'entidad_30',
       'entidad_31', 'entidad_32', 'viv_sel_1', 'viv_sel_2', 'viv_sel_3',
       'viv_sel_4', 'num_hog_1', 'hog_mud_0', 'hog_mud_1', 'hog_mud_2',
       'hog_mud_3', 'n_ren_el_1', 'n_ren_el_2', 'n_ren_el_3',
       'n_ren_el_4', 'n_ren_el_5', 'n_ren_el_6', 'n_ren_el_7',
       'n_ren_el_8', 'n_ren_el_9', 'n_ren_el_10', 'cd_1', 'cd_2', 'cd_3',
       'cd_4', 'cd_5', 'cd_7', 'cd_8', 'cd_9', 'cd_10', 'cd_12', 'cd_13',
       'cd_14', 'cd_15', 'cd_16', 'cd_17', 'cd_18', 'cd_19', 'cd_21',
       'cd_24', 'cd_25', 'cd_26', 'cd_27', 'cd_28',

In [19]:
df=pd.DataFrame(y,columns=nombres)
df

entidad_1  entidad_2  entidad_3  entidad_4  entidad_5  entidad_6  \
0           1.0        0.0        0.0        0.0        0.0        0.0   
1           1.0        0.0        0.0        0.0        0.0        0.0   
2           1.0        0.0        0.0        0.0        0.0        0.0   
3           1.0        0.0        0.0        0.0        0.0        0.0   
4           1.0        0.0        0.0        0.0        0.0        0.0   
...         ...        ...        ...        ...        ...        ...   
1974        0.0        0.0        0.0        0.0        0.0        0.0   
1975        0.0        0.0        0.0        0.0        0.0        0.0   
1976        0.0        0.0        0.0        0.0        0.0        0.0   
1977        0.0        0.0        0.0        0.0        0.0        0.0   
1978        0.0        0.0        0.0        0.0        0.0        0.0   

      entidad_7  entidad_8  entidad_9  entidad_10  ...  p36_2_2  p36_2_3  \
0           0.0        0.0        0.0         0.0  ...      0.0      0.0   
1           0.0        0.0        0.0         0.0  ...      0.0      0.0   
2           0.0        0.0        0.0         0.0  ...      0.0      0.0   
3           0.0        0.0        0.0         0.0  ...      0.0      0.0   
4           0.0        0.0        0.0         0.0  ...      0.0      0.0   
...         ...        ...        ...         ...  ...      ...      ...   
1974        0.0        0.0        0.0         0.0  ...      0.0      0.0   
1975        0.0        0.0        0.0         0.0  ...      0.0      0.0   
1976        0.0        0.0        0.0         0.0  ...      1.0      0.0   
1977        0.0        0.0        0.0         0.0  ...      0.0      1.0   
1978        0.0        0.0        0.0         0.0  ...      0.0      1.0   

      p36_3_0  p36_3_1  p36_3_2  p36_3_3  p36_4_0  p36_4_1  p36_4_2  p36_4_3  
0         0.0      1.0      0.0      0.0      0.0      0.0      1.0      0.0  
1         0.0      1.0      0.0      0.0      0.0      0.0      1.0      0.0  
2         0.0      1.0      0.0      0.0      0.0      0.0      1.0      0.0  
3         0.0      1.0      0.0      0.0      0.0      1.0      0.0      0.0  
4         0.0      1.0      0.0      0.0      0.0      1.0      0.0      0.0  
...       ...      ...      ...      ...      ...      ...      ...      ...  
1974      0.0      1.0      0.0      0.0      0.0      1.0      0.0      0.0  
1975      0.0      1.0      0.0      0.0      0.0      1.0      0.0      0.0  
1976      0.0      0.0      1.0      0.0      0.0      0.0      1.0      0.0  
1977      0.0      0.0      0.0      1.0      0.0      0.0      0.0      1.0  
1978      0.0      0.0      1.0      0.0      0.0      0.0      1.0      0.0  

[1979 rows x 145 columns]

In [20]:
datos_no_categoricos=datos_2022_2.drop(columns=variables_categoricas).reset_index()
datos_no_categoricos=datos_no_categoricos.drop(columns='index')
datos_no_categoricos

edad  nivel  perslecl
0       51      6         2
1       73      2         2
2       52      3         2
3       35      3         2
4       28      4         2
...    ...    ...       ...
1974    37      3         2
1975    65      7         1
1976    54      3         1
1977    87      6         2
1978    65      6         1

[1979 rows x 3 columns]

In [21]:
datos_procesados=pd.concat([datos_no_categoricos,df],axis=1)
datos_procesados

edad  nivel  perslecl  entidad_1  entidad_2  entidad_3  entidad_4  \
0       51      6         2        1.0        0.0        0.0        0.0   
1       73      2         2        1.0        0.0        0.0        0.0   
2       52      3         2        1.0        0.0        0.0        0.0   
3       35      3         2        1.0        0.0        0.0        0.0   
4       28      4         2        1.0        0.0        0.0        0.0   
...    ...    ...       ...        ...        ...        ...        ...   
1974    37      3         2        0.0        0.0        0.0        0.0   
1975    65      7         1        0.0        0.0        0.0        0.0   
1976    54      3         1        0.0        0.0        0.0        0.0   
1977    87      6         2        0.0        0.0        0.0        0.0   
1978    65      6         1        0.0        0.0        0.0        0.0   

      entidad_5  entidad_6  entidad_7  ...  p36_2_2  p36_2_3  p36_3_0  \
0           0.0        0.0        0.0  ...      0.0      0.0      0.0   
1           0.0        0.0        0.0  ...      0.0      0.0      0.0   
2           0.0        0.0        0.0  ...      0.0      0.0      0.0   
3           0.0        0.0        0.0  ...      0.0      0.0      0.0   
4           0.0        0.0        0.0  ...      0.0      0.0      0.0   
...         ...        ...        ...  ...      ...      ...      ...   
1974        0.0        0.0        0.0  ...      0.0      0.0      0.0   
1975        0.0        0.0        0.0  ...      0.0      0.0      0.0   
1976        0.0        0.0        0.0  ...      1.0      0.0      0.0   
1977        0.0        0.0        0.0  ...      0.0      1.0      0.0   
1978        0.0        0.0        0.0  ...      0.0      1.0      0.0   

      p36_3_1  p36_3_2  p36_3_3  p36_4_0  p36_4_1  p36_4_2  p36_4_3  
0         1.0      0.0      0.0      0.0      0.0      1.0      0.0  
1         1.0      0.0      0.0      0.0      0.0      1.0      0.0  
2         1.0      0.0      0.0      0.0      0.0      1.0      0.0  
3         1.0      0.0      0.0      0.0      1.0      0.0      0.0  
4         1.0      0.0      0.0      0.0      1.0      0.0      0.0  
...       ...      ...      ...      ...      ...      ...      ...  
1974      1.0      0.0      0.0      0.0      1.0      0.0      0.0  
1975      1.0      0.0      0.0      0.0      1.0      0.0      0.0  
1976      0.0      1.0      0.0      0.0      0.0      1.0      0.0  
1977      0.0      0.0      1.0      0.0      0.0      0.0      1.0  
1978      0.0      1.0      0.0      0.0      0.0      1.0      0.0  

[1979 rows x 148 columns]

In [22]:
from sklearn.feature_selection import RFE
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.model_selection import cross_validate

In [23]:
x=datos_procesados.drop(columns='perslecl')
y=datos_procesados['perslecl']


Se elige max_depth=3 ya que sobreajusta cuando no se le pasa este parametro (Puede ver un ejemplo  de esto adelante)

In [24]:
estimador_selector= RandomForestClassifier(max_depth=3)
selector_RFE10=RFE(estimador_selector, n_features_to_select=10)
datos_X= selector_RFE10.fit_transform(datos_procesados.drop(columns='perslecl'), datos_procesados['perslecl'])

In [28]:
evaluacion_rfe10_rf = sorted(
    filter(lambda c: c[2], 
        zip(
            datos_procesados.drop(columns='perslecl').columns,
            selector_RFE10.ranking_,
            selector_RFE10.get_support()
        )
    ), key=lambda c: c[1],reverse=True
)

In [29]:
evaluacion_rfe10_rf
campos=[]
for campo in evaluacion_rfe10_rf:
  campos.append(campo[0])

campos

['nivel',
 'p33_1_1',
 'p33_1_2',
 'p33_2_1',
 'p33_2_2',
 'p33_4_2',
 'p34_3_1',
 'p34_4_1',
 'p34_4_2',
 'p34_4_1_0']

In [30]:
campos=['nivel',
 'p33_1',
 'p33_2',
 'p33_4',
 'p34_3',
 'p34_4',
 'p34_4_1',
 ]
valores = diccionario[diccionario.Claves.isin(campos)]
valores

NOMBRE_CAMPO   Claves Catálogo
11                               Nivel de instrucción    nivel    nivel
85  33. En los últimos tres meses, ¿usted asistió ...    p33_1  c_si_no
86  33. En los últimos tres meses, ¿usted asistió ...    p33_2  c_si_no
88  33. En los últimos tres meses, ¿usted asistió ...    p33_4  c_si_no
91  34. ¿Cuándo usted era niño(a) sus padres o tut...    p34_3  c_si_nr
93  34. ¿Cuándo usted era niño(a) sin contar los l...    p34_4  c_si_nr
94  34. ¿Cuándo usted era niño(a)?Aproximadamente ...  p34_4_1   cp34d1

In [45]:
Lista={}
for valor in valores['Claves']:
  Lista[valor]= str(valores[valores['Claves']==valor].NOMBRE_CAMPO.values)[2:-2]

In [46]:
Lista

{'nivel': 'Nivel de instrucción',
 'p33_1': '33. En los últimos tres meses, ¿usted asistió a la sección de libros y revistas de una tienda departamental?        ',
 'p33_2': '33. En los últimos tres meses, ¿usted asistió a un puesto de libros o revistas usados?   ',
 'p33_4': '33. En los últimos tres meses, ¿usted asistió a una librería?',
 'p34_3': '34. ¿Cuándo usted era niño(a) sus padres o tutores le leían?    ',
 'p34_4': '34. ¿Cuándo usted era niño(a) sin contar los libros de texto, había libros en su casa?',
 'p34_4_1': '34. ¿Cuándo usted era niño(a)?Aproximadamente había…'}

In [47]:
Lista={'nivel': 'Nivel de instrucción',
 'p33_1_1': '33. En los últimos tres meses, ¿usted asistió a la sección de libros y revistas de una tienda departamental? Sí',
 'p33_1_2': '33. En los últimos tres meses, ¿usted asistió a la sección de libros y revistas de una tienda departamental? No',
 'p33_2_1': '33. En los últimos tres meses, ¿usted asistió a un puesto de libros o revistas usados? Sí  ',
 'p33_2_2': '33. En los últimos tres meses, ¿usted asistió a un puesto de libros o revistas usados? No ',
 'p33_4_2': '33. En los últimos tres meses, ¿usted asistió a una librería? No',
 'p34_3_1': '34. ¿Cuándo usted era niño(a) sus padres o tutores le leían?  Sí  ',
 'p34_4_1': '34. ¿Cuándo usted era niño(a) sin contar los libros de texto, había libros en su casa? Sí',
 'p34_4_1_1': '34. ¿Cuándo usted era niño(a)?Aproximadamente había… de 1 a 25 libros'}

In [48]:
def evaluar_modelo_f1(estimador, X, y):
    resultados_estimador = cross_validate(estimador, X, y,
                     scoring='f1', cv=10, return_train_score=True)
    return resultados_estimador
def evaluar_modelo_roc(estimador, X, y):
    resultados_estimador = cross_validate(estimador, X, y,
                     scoring='roc_auc', cv=10, return_train_score=True)
    return resultados_estimador

def promedios_cv(puntuacion):
  for dato in puntuacion:
    puntuacion[dato]=np.mean(puntuacion.get(dato))
  return puntuacion

In [71]:
puntuacion1=evaluar_modelo_f1(RandomForestClassifier(),x,y)
puntuacion1_a=evaluar_modelo_roc(RandomForestClassifier(),x,y)

In [85]:
Scores=pd.DataFrame(promedios_cv(puntuacion1), index=['RFC_f1'])
Scores=pd.concat([Scores, pd.DataFrame(promedios_cv(puntuacion1_a), index=['RFC_roc'])], axis=0)

In [86]:
Scores

fit_time  score_time  test_score  train_score
RFC_f1   0.346202    0.018444    0.709523          1.0
RFC_roc  0.426105    0.026974    0.673093          1.0

In [87]:
puntuacion=evaluar_modelo_f1(RandomForestClassifier(max_depth=3),x,y)
puntuacion_a=evaluar_modelo_roc(RandomForestClassifier(max_depth=3),x,y)

In [88]:
Scores=pd.concat([Scores, pd.DataFrame(promedios_cv(puntuacion), index=['RFC_f1_max3']), pd.DataFrame(promedios_cv(puntuacion_a), index=['RFC_roc_max3'])], axis=0)

In [89]:
Scores

fit_time  score_time  test_score  train_score
RFC_f1        0.346202    0.018444    0.709523     1.000000
RFC_roc       0.426105    0.026974    0.673093     1.000000
RFC_f1_max3   0.178722    0.015244    0.769876     0.785525
RFC_roc_max3  0.175246    0.014867    0.745318     0.781002

In [90]:
puntuacion2=evaluar_modelo_f1(RandomForestClassifier(max_depth=3),datos_X,y)
puntuacion2_a=evaluar_modelo_roc(RandomForestClassifier(max_depth=3),datos_X,y)

In [93]:
Scores=pd.concat([Scores, pd.DataFrame(promedios_cv(puntuacion2), index=['RFC_f1_max3_datosX']), pd.DataFrame(promedios_cv(puntuacion2_a), index=['RFC_roc_max3_datosX'])], axis=0)
Scores

fit_time  score_time  test_score  train_score
RFC_f1               0.346202    0.018444    0.709523     1.000000
RFC_roc              0.426105    0.026974    0.673093     1.000000
RFC_f1_max3          0.178722    0.015244    0.769876     0.785525
RFC_roc_max3         0.175246    0.014867    0.745318     0.781002
RFC_f1_max3_datosX   0.150620    0.012728    0.760234     0.766625
RFC_roc_max3_datosX  0.148315    0.012918    0.760554     0.767606

In [94]:
puntuacion3=evaluar_modelo_f1(SVC(),datos_X, y)
puntuacion3_a=evaluar_modelo_roc(SVC(),datos_X, y)

In [95]:
Scores=pd.concat([Scores, pd.DataFrame(promedios_cv(puntuacion3), index=['SVC_f1']), pd.DataFrame(promedios_cv(puntuacion3_a), index=['SVC_roc'])], axis=0)
Scores

fit_time  score_time  test_score  train_score
RFC_f1               0.346202    0.018444    0.709523     1.000000
RFC_roc              0.426105    0.026974    0.673093     1.000000
RFC_f1_max3          0.178722    0.015244    0.769876     0.785525
RFC_roc_max3         0.175246    0.014867    0.745318     0.781002
RFC_f1_max3_datosX   0.150620    0.012728    0.760234     0.766625
RFC_roc_max3_datosX  0.148315    0.012918    0.760554     0.767606
SVC_f1               0.132885    0.015963    0.770882     0.771756
SVC_roc              0.139391    0.018421    0.742610     0.754258